# This extend our general Ruff rules specifically for aiohomematic_test_support
extend = "../pyproject.toml"

[lint.isort]
known-first-party = [
    "aiohomematic",
    "aiohomematic_test_support"
]

known-third-party = [
    "orjson",
    "voluptuous",
]